version: '3.8'

services:

  db:
    image: postgres:16
    container_name: pivo-backend-db
    ports:
      - '5432:5432'
    environment:
    
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      
networks:
  default:
    name: pivobackend_default
    
volumes:
  data: